# Syntax

attribute = "Gray10"
type = "Gray10"
"type.builtin" = "Cyan30"
constructor = "Cyan30"
constant = "Gray10"
"constant.builtin" = "Cyan30"
"constant.builtin.boolean" = "Gray10"
"constant.character" = "Gray10"
"constant.character.escape" = "Cyan30"
"constant.numeric.integer" = "Gray10"
"constant.numeric.float" = "Gray10"
string = "Green30"
"string.regexp" = "Cyan30"
"string.special.url" = { modifiers = ["underlined"] }
comment = "Gray50"
variable = "Gray10"
"variable.builtin" = "Cyan30"
label = { fg = "Gray10", modifiers = ["bold"] }
punctuation = "Gray10"
"punctuation.special" = "Cyan30"
keyword = { fg = "Gray10", modifiers = ["bold"] }
operator = "Gray10"
function = "Cyan30"
"function.builtin" = "Cyan30"
tag = "Cyan30"
"tag.builtin" = "Cyan30"
special = "Cyan30"
markup = "Cyan30"
"markup.heading" = { fg = "Gray10", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { modifiers = ["underlined"] }
"diff.plus" = "Green30"
"diff.minus" = "Red50"
"diff.delta" = "Cyan30"

# Interface

"ui.background" = { bg = "Gray90" }
"ui.background.separator" = { fg = "Gray70" }
"ui.cursor" = { fg = "Gray90", bg = "Gray10" }
"ui.cursor.match" = { bg = "Gray70", modifiers = ["bold"] }
"ui.debug.breakpoint" = { fg = "Cyan30" }
"ui.debug.active" = { fg = "Cyan30" }
"ui.linenr" = { fg = "Gray70" }
"ui.linenr.selected" = { modifiers = ["bold"] }
"ui.statusline" = { fg = "Gray10", bg = "Gray80" }

#"ui.statusline.inactive" = { fg = "lavender", bg = "revolver" }
#"ui.popup" = { bg = "revolver" }
#"ui.window" = { fg = "bossanova" }
#"ui.help" = { bg = "#7958DC", fg = "#171452" }
#"ui.text" = { fg = "lavender" }
#"ui.text.focus" = { fg = "white" }
#"ui.text.inactive" = "sirocco"
#"ui.virtual" = { fg = "comet" }
#"ui.virtual.ruler" = { bg = "revolver" }
#"ui.virtual.jump-label" = { fg = "apricot", modifiers = ["bold"] }

#"ui.virtual.indent-guide" = { fg = "comet" }

"ui.selection" = { bg = "#540099" }
#"ui.selection.primary" = { bg = "#540099" }
# TODO: namespace ui.cursor as ui.selection.cursor?
#"ui.cursor.select" = { bg = "delta" }
#"ui.cursor.insert" = { bg = "white" }
#"ui.cursor.primary.select" = { bg = "delta" }
#"ui.cursor.primary.insert" = { bg = "white" }
#"ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
#"ui.cursorline.primary" = { bg = "bossanova" }
#"ui.highlight" = { bg = "bossanova" }
#"ui.highlight.frameline" = { bg = "#634450" }
#"ui.menu" = { fg = "lavender", bg = "revolver" }
#"ui.menu.selected" = { fg = "revolver", bg = "white" }
#"ui.menu.scroll" = { fg = "lavender", bg = "comet" }

#"diagnostic.hint" = { underline = { color = "silver", style = "curl" } }
#"diagnostic.info" = { underline = { color = "delta", style = "curl" } }
#"diagnostic.warning" = { underline = { color = "lightning", style = "curl" } }
#"diagnostic.error" = { underline = { color = "apricot", style = "curl" } }
#"diagnostic.unnecessary" = { modifiers = ["dim"] }
#"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


[palette]
Gray10 = "#f2f4f8"
Gray30 = "#c1c7cd"
Gray50 = "#878d96"
Gray70 = "#4d5358"
Gray80 = "#343a3f"
Gray90 = "#21272a"
Cyan30 = "#82cfff"
Green30 = "#6fdc8c"
Red50 = "#fa4d56"
