# Global Anchors
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=20
awesome_brands: &awesome_brands Font Awesome 6 Brands:pixelsize=20
symbols: &symbols Symbols Nerd Font:style=Regular:pixelsize=29
monofont: &monofont IBM Plex Mono:pixelsize=22

# border-interactive/support-info (Blue 50)
blue: &blue 4589ffff

# (Gray 50)
gray: &gray 878d96ff

# support-error (Red 50)
red: &red fa4d56ff

# support-warning (Yellow)
yellow: &yellow f1c21bff

# Gray 100
gray100: &gray100 121619ff

# This is THE bar configuration
bar:
  height: 44
  location: top
  margin: 6

  # Default font
  font: IBM Plex Sans:pixelsize=22
  
  # text-primary (Gray 10)
  foreground: f2f4f8ff

  # background (Gray 100)
  background: 121619ff

  left:
    - label:
        content:
          string: {text: "", font: *symbols, foreground: *blue, margin: 11}

    - i3:
        content:
          current:
            map:
              default: {empty: {}} 
              conditions:
                mode == "window": {string: {text: "{mode}", foreground: *yellow, font: *monofont, margin: 11}}
                mode == "notify": {string: {text: "{mode}", foreground: *yellow, font: *monofont, margin: 11}}
                mode == "volume": {string: {text: "{mode}", foreground: *yellow, font: *monofont, margin: 11}}
                mode == "power":
                  list:
                    items:
                      - string: {text: "{mode}", foreground: *yellow, font: *monofont, margin: 11}
                mode == "music": 
                  list:
                    items:
                      - string: {text: "{mode}", foreground: *yellow, font: *monofont, margin: 11}
    - i3:
        anchors: 
          - string: &sway_common {text: "{name}", margin: 11, on-click: "swaymsg --quiet workspace {name}"}
          - string: &sway_focus {<<: *sway_common, deco: {overline: {color: *blue, size: 2}}}
          - string: &sway_dim {<<: *sway_common, foreground: *gray}
          - string: &sway_urgent {<<: *sway_dim, deco: {overline: {color: *red, size: 2}}}  
        content:
          "":
            map:
              conditions:
                state == focused: {string: {<<: *sway_focus}}
                state == unfocused: {string: {<<: *sway_dim}}
                state == invisible: {string: {<<: *sway_dim}}
                state == urgent: {string: {<<: *sway_urgent}}
        sort: native 

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                map:
                  default: 
                    - string: {text: "  ", font: *symbols, foreground: *blue, left-margin: 44}
                    - string: {text: "{app-id}"}
                  conditions:
                    app-id == foot: 
                      list:
                        items:
                          - string: {text: "  ", font: *symbols, foreground: *blue, left-margin: 44}
                          - string: {text: "{app-id}"}
                    app-id == firefox:
                      list:
                        items:
                          - string: {text: "  ", font: *symbols, foreground: *blue, left-margin: 44}
                          - string: {text: "{app-id}"}                            
  center:
    - clock:
        time-format: "%R"
        date-format: "%a  %b %d"
        content:
          string: {text: "{date}  {time}"}
  right:  
    - script:
        path: /usr/bin/playerctl
        args:
          - "--follow"
          - "metadata"
          - "-f"
          - |
            status|string|{{status}}
            artist|string|{{artist}}
            title|string|{{title}}
        poll-interval: 2500
        content:
          map:
            default: {empty: {}}
            conditions:
              status == Stopped: {empty: {}}
              status == Paused:
                list:
                  items:
                    - string: {text: "  ", font: *symbols, foreground: *gray} 
                    - string: {text: "{artist} - {title}", foreground: *gray, max: 31, right-margin: 44}
              status == Playing: 
                list:
                  items:
                    - string: {text: "  ", font: *symbols}
                    - string: {text: "{artist} - {title}", max: 31, right-margin: 44}
    - pipewire:
        content:
          map:
            conditions:
              type == sink:
                map:
                  conditions:
                    (form_factor == "headphones") && (~muted):
                      list:
                        items:
                          - string: {text: "󰋋 ", font: *symbols, left-margin: 11}
                          - string: {text: "{linear_volume}%", right-margin: 11}
                    (form_factor == "headphones") && (muted):
                      list:
                        items:
                          - string: {text: "󰟎 ", font: *symbols, foreground: *gray, left-margin: 11}
                          - string: {text: "{linear_volume}%", foreground: *gray, right-margin: 11}                   
                    (form_factor != "headphones") && (muted):
                      list:
                        items:
                          - string: {text: "󰝟 ", font: *symbols, foreground: *gray, left-margin: 11}
                          - string: {text: "{linear_volume}%", foreground: *gray, right-margin: 11}
                  default:
                    list:
                      items:
                        - ramp:
                            tag: linear_volume
                            items:
                              - string: {text: "󰕿 ", font: *symbols, left-margin: 11}
                              - string: {text: "󰖀 ", font: *symbols, left-margin: 11}
                              - string: {text: "󰕾 ", font: *symbols, left-margin: 11}
                        - string: {text: "{linear_volume}%", right-margin: 11}
    - network:   
        name: enp42s0
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default: {string: {text: , font: *awesome, margin: 11}}
                  conditions:
                    ipv4 == "": {string: {text: , font: *awesome, foreground: *red, margin: 11}}
