# Global Anchors
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=20
symbols: &symbols Symbols Nerd Font:style=Regular:pixelsize=29
monofont: &monofont IBM Plex Mono:pixelsize=22

# (Blue 50)
blue50: &blue50 4589ffff

# (Red 50)
red50: &red50 fa4d56ff

# (Yellow 30)
yellow30: &yellow30 f1c21bff

# Gray 90
gray90: &gray90 21272aff

# Gray 70
gray70: &gray70 4d5358ff

# Gray 50 (Tertiary Text)
gray50: &gray50 878d96ff

# Gray 10 
gray10: &gray10 f2f4f8ff

# This is THE bar configuration
bar:
  height: 44
  location: top
  margin: 7

  # Default font
  font: IBM Plex Sans:pixelsize=22
  
  # text-primary
  foreground: *gray10

  # background 
  background: *gray90

  border:
    left-width: 0
    right-width: 0
    top-width: 0
    bottom-width: 2
    color: *gray70
  
  left:
    - label:
        content:
          string: {text: "", font: *symbols, foreground: *blue50, margin: 11}

    - i3:
        content:
          current:
            map:
              default: {empty: {}} 
              conditions:
                mode == "window": {string: {text: "{mode}", foreground: *yellow30, font: *monofont, margin: 11}}
                mode == "notify": {string: {text: "{mode}", foreground: *yellow30, font: *monofont, margin: 11}}
                mode == "volume": {string: {text: "{mode}", foreground: *yellow30, font: *monofont, margin: 11}}
                mode == "power": {string: {text: "{mode}", foreground: *yellow30, font: *monofont, margin: 11}}
                mode == "music": {string: {text: "{mode}", foreground: *yellow30, font: *monofont, margin: 11}}
    - i3:
        anchors: 
          - string: &sway_common {text: "{name}", margin: 11, on-click: "swaymsg --quiet workspace {name}"}
          - string: &sway_focus {<<: *sway_common, deco: {overline: {color: *blue50, size: 2}}}
          - string: &sway_dim {<<: *sway_common, foreground: *gray50}
          - string: &sway_urgent {<<: *sway_dim, deco: {overline: {color: *red50, size: 2}}}  
        content:
          "":
            map:
              conditions:
                state == focused: {string: {<<: *sway_focus}}
                state == unfocused: {string: {<<: *sway_dim}}
                state == invisible: {string: {<<: *sway_dim}}
                state == urgent: {string: {<<: *sway_urgent}}
        sort: native 

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                map:
                  default: 
                    - string: {text: "  ", font: *symbols, foreground: *blue50, left-margin: 44}
                    - string: {text: "{app-id}"}
                  conditions:
                    app-id == foot: 
                      list:
                        items:
                          - string: {text: "  ", font: *symbols, foreground: *blue50, left-margin: 44}
                          - string: {text: "{app-id}"}
                    app-id == firefox:
                      list:
                        items:
                          - string: {text: "  ", font: *symbols, foreground: *blue50, left-margin: 44}
                          - string: {text: "{app-id}"}                            
  center:
    - clock:
        time-format: "%R"
        date-format: "%a  %b %d"
        content:
          string: {text: "{date}  {time}"}
  right:  
    - script:
        path: /usr/bin/playerctl
        args:
          - "--follow"
          - "metadata"
          - "-f"
          - |
            status|string|{{status}}
            artist|string|{{artist}}
            title|string|{{title}}
        poll-interval: 2500
        content:
          map:
            default: {empty: {}}
            conditions:
              status == Stopped: {empty: {}}
              status == Paused:
                list:
                  items:
                    - string: {text: "  ", font: *symbols, foreground: *gray50} 
                    - string: {text: "{artist} - {title}", foreground: *gray50, max: 31, right-margin: 44}
              status == Playing: 
                list:
                  items:
                    - string: {text: "  ", font: *symbols}
                    - string: {text: "{artist} - {title}", max: 31, right-margin: 44}
    - pipewire:
        content:
          map:
            conditions:
              type == sink:
                map:
                  conditions:
                    (form_factor == "headphones") && (~muted):
                      list:
                        items:
                          - string: {text: "󰋋 ", font: *symbols, left-margin: 11}
                          - string: {text: "{linear_volume}%", right-margin: 11}
                    (form_factor == "headphones") && (muted):
                      list:
                        items:
                          - string: {text: "󰟎 ", font: *symbols, foreground: *gray50, left-margin: 11}
                          - string: {text: "{linear_volume}%", foreground: *gray50, right-margin: 11}                   
                    (form_factor != "headphones") && (muted):
                      list:
                        items:
                          - string: {text: "󰝟 ", font: *symbols, foreground: *gray50, left-margin: 11}
                          - string: {text: "{linear_volume}%", foreground: *gray50, right-margin: 11}
                  default:
                    list:
                      items:
                        - ramp:
                            tag: linear_volume
                            items:
                              - string: {text: "󰕿 ", font: *symbols, left-margin: 11}
                              - string: {text: "󰖀 ", font: *symbols, left-margin: 11}
                              - string: {text: "󰕾 ", font: *symbols, left-margin: 11}
                        - string: {text: "{linear_volume}%", right-margin: 11}
    - network:   
        name: enp42s0
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default: {string: {text: , font: *awesome, margin: 11}}
                  conditions:
                    ipv4 == "": {string: {text: , font: *awesome, foreground: *red50, margin: 11}}
