theme="carbyne"


[editor]
#cursorline = true
#rulers = [80]
#bufferline = multiple
color-modes = true
text-width = 80
popup-border = "none"


#[editor.statusline]
#left
#center
#right


[editor.lsp]
enable = true


[editor.cursor-shape]
insert = "bar"

#[editor.whitespace]
#render = "all"

#[editor.indent-guides]
#render = true
