theme="carbyne"

[editor]
#rulers = [80]
#cursorline = true
#cursorcolumn = true
color-modes = true
#bufferline = "always"

#[editor.whitespace]
#render = "all"

#[editor.indent-guides]
#render = true
